# 预备知识

In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[6.2981e+31, 6.2498e-43, 6.2981e+31],
        [6.2498e-43, 6.2967e+31, 6.2498e-43],
        [6.2967e+31, 6.2498e-43, 6.2967e+31],
        [6.2498e-43, 6.2967e+31, 6.2498e-43],
        [6.2972e+31, 6.2498e-43, 6.2972e+31]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5228, 0.3767, 0.6568],
        [0.8697, 0.9208, 0.2569],
        [0.4546, 0.4451, 0.0418],
        [0.5522, 0.4856, 0.4677],
        [0.6637, 0.6297, 0.7822]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3847, -0.0783,  0.5518],
        [ 2.3079, -0.0698, -1.7801],
        [-1.7503, -1.3711,  0.5684],
        [-0.9721,  0.1164,  1.1777],
        [ 0.1999, -1.4738,  0.0077]])


In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1232,  0.7693,  0.8950],
        [ 3.2808,  0.8512, -1.1968],
        [-1.2218, -1.3293,  1.0466],
        [-0.4675,  0.6884,  1.7449],
        [ 0.2403, -0.8124,  0.3102]])


In [9]:
print(torch.add(x, y))

tensor([[ 1.1232,  0.7693,  0.8950],
        [ 3.2808,  0.8512, -1.1968],
        [-1.2218, -1.3293,  1.0466],
        [-0.4675,  0.6884,  1.7449],
        [ 0.2403, -0.8124,  0.3102]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1232,  0.7693,  0.8950],
        [ 3.2808,  0.8512, -1.1968],
        [-1.2218, -1.3293,  1.0466],
        [-0.4675,  0.6884,  1.7449],
        [ 0.2403, -0.8124,  0.3102]])


In [11]:
y.add_(x)
print(y)

tensor([[ 1.1232,  0.7693,  0.8950],
        [ 3.2808,  0.8512, -1.1968],
        [-1.2218, -1.3293,  1.0466],
        [-0.4675,  0.6884,  1.7449],
        [ 0.2403, -0.8124,  0.3102]])


In [12]:
y = x[0, :]
y += 1
print(y)
print(x[0, :])

tensor([1.3847, 0.9217, 1.5518])
tensor([1.3847, 0.9217, 1.5518])


In [13]:
y = x.view(15)
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [14]:
x += 1
print(x)
print(y)

tensor([[ 2.3847,  1.9217,  2.5518],
        [ 3.3079,  0.9302, -0.7801],
        [-0.7503, -0.3711,  1.5684],
        [ 0.0279,  1.1164,  2.1777],
        [ 1.1999, -0.4738,  1.0077]])
tensor([ 2.3847,  1.9217,  2.5518,  3.3079,  0.9302, -0.7801, -0.7503, -0.3711,
         1.5684,  0.0279,  1.1164,  2.1777,  1.1999, -0.4738,  1.0077])


In [15]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.3847,  0.9217,  1.5518],
        [ 2.3079, -0.0698, -1.7801],
        [-1.7503, -1.3711,  0.5684],
        [-0.9721,  0.1164,  1.1777],
        [ 0.1999, -1.4738,  0.0077]])
tensor([ 2.3847,  1.9217,  2.5518,  3.3079,  0.9302, -0.7801, -0.7503, -0.3711,
         1.5684,  0.0279,  1.1164,  2.1777,  1.1999, -0.4738,  1.0077])


In [16]:
x = torch.arange(1, 3).view(1, 2)
print(x)

y = torch.arange(1, 4).view(3, 1)
print(y)

print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [17]:
a = torch.ones(5)
b = a.numpy()

print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [18]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [19]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

In [20]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [21]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [22]:
print(x.is_leaf, y.is_leaf)

True False


In [23]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [24]:
a = torch.randn(2, 2)
a = ((a * 3) / (a -1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [25]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [26]:
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [27]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [28]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [29]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2 
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad) # True
print(y2, y2.requires_grad) # False
print(y3, y3.requires_grad) # True

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [30]:
y3.backward()
print(x.grad)

tensor(2.)


In [31]:
x = torch.ones(1,requires_grad=True)

print(x.data) # 还是一个tensor
print(x.data.requires_grad) # 但是已经是独立于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x) # 更改data的值也会影响tensor的值
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
